"""10-Q Insight — Streamlit dashboard.

Run with:  streamlit run app.py

UI patterns (st.cache_resource model loading, sidebar inputs, st.metric
columns, wide layout) adapted from week6-seminar.ipynb Challenge 4
"Streamlit Credit Scoring Dashboard" and chapter-09-advicetech/streamlit_app.py
(Hric & Lin 2026).
"""

import json

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

import config
from market_data import surprise_for_period
from pipeline import analyse_filing
from sec_edgar import EdgarError, fetch_filing_html, list_10q_filings
from sentiment import load_pipeline

st.set_page_config(page_title="10-Q Insight", page_icon="📊", layout="wide")

SENTIMENT_COLORS = {
    "positive": "#2e7d32",
    "neutral": "#9e9e9e",
    "negative": "#c62828",
}

CATEGORY_META = [
    ("financial_highlights", "💰 Financial Highlights"),
    ("business_drivers", "⚙️ Business Drivers"),
    ("management_outlook", "🔭 Management Outlook"),
    ("material_risks", "⚠️ Material Risks"),
]

TONE_BADGES = {
    "positive": "🟢 Positive",
    "neutral": "⚪ Neutral",
    "negative": "🔴 Negative",
    "mixed": "🟡 Mixed",
}


@st.cache_resource(show_spinner="Loading FinBERT (first run downloads ~440 MB)…")
def get_finbert():
    """Load FinBERT once per server process, not once per click."""
    return load_pipeline()


@st.cache_data(ttl=3600, show_spinner=False)
def cached_filings(ticker: str):
    """Cache the filing list per ticker for an hour (EDGAR fair access)."""
    return list_10q_filings(ticker)


@st.cache_data(ttl=3600, show_spinner=False)
def cached_filing_html(accession: str, _filing):
    """Cache filing HTML; key = accession (leading underscore skips hashing _filing)."""
    return fetch_filing_html(_filing)


def render_summary(analysis: dict) -> None:
    """Render the executive summary section of a completed filing analysis"""
    summary = analysis["executive_summary"]
    meta = analysis["meta"]

    if summary.get("generated_by") == "finbert-heuristic-mock":
        note = "Mock mode: summary assembled from FinBERT evidence. "
        if summary.get("llm_error"):
            st.error(f"LLM call failed — {summary['llm_error']}. {note}")
        else:
            st.warning(f"{note}Set an LLM API key in .env for LLM summaries.")

    assessment = summary.get("overall_assessment", {})
    surprise = analysis.get("earnings_surprise")
    has_surprise = bool(
        surprise
        and surprise.get("estimate") is not None
        and surprise.get("actual") is not None
    )

    left, mid, right = st.columns([1, 1, 2])
    with left:
        st.markdown("**Overall tone**")
        st.markdown(f"### {TONE_BADGES.get(assessment.get('tone'), '🟡 Mixed')}")

        if assessment.get("tone_basis"):
            st.caption(assessment["tone_basis"])
    with mid:
        if has_surprise:
            pct = surprise.get("surprise_pct")
            st.markdown("**EPS vs consensus**")
            if pct is not None:
                icon = "🟢" if pct > 0 else "🔴" if pct < 0 else "⚪"
                colour = "green" if pct > 0 else "red" if pct < 0 else "gray"
                label = "Beat" if pct > 0 else "Miss" if pct < 0 else "In-line"
                st.markdown(f"### {icon} :{colour}[{label} {pct:+.1f}%]")
            st.markdown(
                f"{surprise['actual']:.2f} vs {surprise['estimate']:.2f} est"
            )
    with right:
        if assessment.get("rationale"):
            st.markdown("**LLM assessment**")
            st.markdown(f"> {assessment['rationale']}")
            llm_tone = assessment.get("llm_tone")
            if llm_tone and llm_tone != assessment.get("tone"):
                st.caption(
                    f"Model's own tone read: {llm_tone} — badge uses the "
                    "deterministic FinBERT score."
                )

    if has_surprise:
        st.caption(
            "Market context from Finnhub earnings surprises (street consensus "
            "basis) — independent of the sentiment model. Not investment advice."
        )

    cols = st.columns(2)
    for i, (key, title) in enumerate(CATEGORY_META):
        with cols[i % 2]:
            st.subheader(title)
            items = summary.get(key) or []
            if not items:
                st.caption("No content identified for this category.")
            for item in items:
                st.markdown(f"- **{item['point']}**")
                if item.get("evidence"):
                    st.caption(f"“{item['evidence']}”")

    st.caption(
        f"Summary generated by `{summary.get('generated_by')}` · "
        f"Source: [{meta['form']} on SEC EDGAR]({meta['source_url']})"
    )


def render_sentiment(analysis: dict) -> None:
    """Render the sentiment section of a completed filing analysis"""
    rows = [
        {
            "Section": data["title"],
            "Sentences": data["aggregate"]["n_sentences"],
            "positive": data["aggregate"]["shares"]["positive"],
            "neutral": data["aggregate"]["shares"]["neutral"],
            "negative": data["aggregate"]["shares"]["negative"],
            "Net": data["aggregate"]["net_score"],
            "Weighted": data["aggregate"].get("weighted_score", 0.0),
        }
        for data in analysis["sections"].values()
    ]
    df = pd.DataFrame(rows)

    metric_cols = st.columns(len(rows) or 1)
    for col, row in zip(metric_cols, rows):
        short = row["Section"].split("—")[-1].strip()
        col.metric(
            short,
            f"{row['Net']:+.2f}",
            f"wtd {row['Weighted']:+.2f} · {row['Sentences']} sents",
            delta_color="off",
        )

    fig = go.Figure()
    for label in ("positive", "neutral", "negative"):
        fig.add_bar(
            y=df["Section"], x=df[label], name=label.capitalize(),
            orientation="h", marker_color=SENTIMENT_COLORS[label],
        )
    fig.update_layout(
        barmode="stack",
        title="Sentence-level FinBERT sentiment by section",
        xaxis_tickformat=".0%",
        height=90 + 60 * len(rows),
        margin=dict(l=10, r=10, t=50, b=10),
        legend=dict(orientation="h", y=-0.15),
    )
    st.plotly_chart(fig, use_container_width=True)

    st.caption(
        "Net score = (positive − negative) ÷ total sentences; weighted score "
        "= mean of per-sentence P(positive) − P(negative). Both range −1 to "
        "+1. Neutral dominance is normal in regulatory filings; overall tone "
        "uses MD&A only (Part II sections are structurally negative)."
    )


def render_evidence(analysis: dict) -> None:
    """Render the evidence section of a completed filing analysis"""
    for data in analysis["sections"].values():
        agg = data["aggregate"]
        with st.expander(
            f"{data['title']} — net {agg['net_score']:+.2f}, "
            f"wtd {agg.get('weighted_score', 0.0):+.2f}, "
            f"{agg['n_sentences']} sentences"
        ):
            pos_col, neg_col = st.columns(2)
            with pos_col:
                st.markdown("**Most positive sentences**")
                for row in agg["top_positive"] or []:
                    st.success(f"{row['sentence']}\n\n`{row['confidence']:.2f}`")
                if not agg["top_positive"]:
                    st.caption("None detected.")
            with neg_col:
                st.markdown("**Most negative sentences**")
                for row in agg["top_negative"] or []:
                    st.error(f"{row['sentence']}\n\n`{row['confidence']:.2f}`")
                if not agg["top_negative"]:
                    st.caption("None detected.")
            st.dataframe(
                pd.DataFrame(data["sentences"]),
                use_container_width=True, height=240,
            )


def main() -> None:
    st.title("📊 10-Q Insight")
    st.markdown(
        "AI-assisted first-pass review of SEC 10-Q filings: section-level "
        "**FinBERT** sentiment with supporting excerpts, plus a structured "
        "executive summary. Built for junior analysts — decision support, "
        "**not** investment advice."
    )

    with st.sidebar:
        st.header("Filing selection")
        ticker = st.text_input(
            "US ticker", placeholder="e.g. AAPL, MSFT, NVDA",
            help="US-listed companies only. Class shares use a dash (BRK-B).",
        )
        filings = None
        if ticker:
            try:
                filings = cached_filings(ticker)
            except EdgarError as exc:
                st.error(str(exc))
        filing = None
        if filings:
            st.success(f"{filings[0].company} — {len(filings)} recent 10-Qs")
            filing = st.selectbox("10-Q filing", filings, format_func=lambda f: f.label)
        run = st.button(
            "Analyse filing", type="primary",
            disabled=filing is None, use_container_width=True,
        )

        st.divider()
        provider = config.active_provider()
        if provider != "mock":
            st.caption(f"🟢 LLM summaries: {provider} · `{config.model_for(provider)}`")
        else:
            st.caption("🟡 Mock mode — set an LLM API key in `.env`")
        st.caption(f"Sentiment model: `{config.SENTIMENT_MODEL}`")
        with st.expander("Methodology"):
            st.markdown(
                "1. Filing fetched from **SEC EDGAR** (official JSON APIs)\n"
                "2. Item sections located by heading patterns\n"
                "3. Sentences scored with **FinBERT** in batches\n"
                "4. Executive summary generated by an LLM constrained to a "
                "**standard JSON schema**, quoting verbatim evidence\n"
                "5. Full result exportable as one JSON document"
            )

    if run and filing is not None:
        try:
            with st.status("Analysing filing…", expanded=True) as status:
                st.write("Fetching filing from SEC EDGAR…")
                html = cached_filing_html(filing.accession, filing)
                st.write("Loading FinBERT model…")
                nlp = get_finbert()
                analysis = analyse_filing(filing, html, nlp, progress=st.write)
                analysis["earnings_surprise"] = surprise_for_period(
                    filing.ticker, filing.report_date
                )
                status.update(label="Analysis complete", state="complete", expanded=False)
            st.session_state["analysis"] = analysis
        except EdgarError as exc:
            st.error(str(exc))
        except ValueError as exc:
            st.error(str(exc))
        except Exception as exc:  # noqa: BLE001 — surface, don't crash
            st.error(f"Unexpected error during analysis: {exc}")

    analysis = st.session_state.get("analysis")
    if analysis is None:
        st.info("Enter a ticker in the sidebar, pick a 10-Q, and click **Analyse filing**.")
        return

    meta = analysis["meta"]

    if filing is not None and meta["accession"] != filing.accession:
        st.info(
            "Showing the previous analysis. Click **Analyse filing** to "
            "analyse the newly selected filing."
        )

    st.header(
        f"{meta['company']} ({meta['ticker']}) — {meta['form']}, "
        f"period ending {meta['report_date']}"
    )

    tab_summary, tab_sentiment, tab_evidence, tab_export = st.tabs(
        ["Executive Summary", "Section Sentiment", "Evidence Explorer", "JSON Export"]
    )
    with tab_summary:
        render_summary(analysis)
    with tab_sentiment:
        render_sentiment(analysis)
    with tab_evidence:
        render_evidence(analysis)
    with tab_export:
        st.markdown(
            "The complete analysis — metadata, section sentiment, and the "
            "executive summary — as one standardised JSON document."
        )
        payload = json.dumps(analysis, indent=2, ensure_ascii=False)
        st.download_button(
            "Download analysis JSON", payload,
            file_name=f"{meta['ticker']}_{meta['report_date']}_10q_analysis.json",
            mime="application/json",
        )
        st.json(analysis, expanded=False)

    st.divider()
    st.caption(
        "Educational tool built for UNSW FINS5557. Outputs are AI-generated, "
        "may contain errors, and do not constitute financial advice."
    )


if __name__ == "__main__":
    main()